### ISSUE TITLE
Inaccurate and not helpful error message "SQLite exited with error code 1"

### ISSUE THREAD

**Issue by xuchunyang** [cireu/counsel-ffdata#2]
I've just installed this package and immediately type  `M-x counsel-ffdata-firefox-bookmarks`, I get

> if: SQLite exited with error code 1

Firstly, the error message is not helpful, the error code tells almost nothing, it should say what's the error really about. I suggest some change like the following

```diff
-(error "SQLite exited with error code %d" errno)
+(error "SQLite failed: %s" (buffer-string))
```

then the error message becomes

> SQLite failed: no such table: moz_bookmarks

It looks much better to me as I know what's the error.

Secondly, I notice `counsel-ffdata-database-path` is still nil because I'm using macOS, so the sqlite3 command should not run at all, `M-x counsel-ffdata-firefox-bookmarks` should fail early (maybe with `user-error`) and tell me that `counsel-ffdata-database-path` is not set.

**Comment by cireu** [comment]
On it.
