### ISSUE TITLE
How much memory your counsel-ffdata--cache takes?

### ISSUE THREAD

**Issue by xuchunyang** [cireu/counsel-ffdata#4]
According to the README, you have many bookmarks and history records, for curiosity I would like to know how many memory `counsel-ffdata--cache` takes. One way to find out is

    M-x pp-eval-expression counsel-ffdata--cache

and see the buffer size.

**Comment by cireu** [comment]
Is memory usage really a big problem? For me, 67484 record in cache. After I run

```elisp
(setq counsel-ffdata--cache (make-hash-table :test #'equal))
(garbage-collect)
```
I don't found obvious decrease of memory usage.

**Comment by cireu** [comment]
Surely I can change the working method from "query once and cache" to "connect to sqlite and send query for each completion session". But it seems to be meaningless because we have to copy the database when Firefox is running so real-time completion is impossible.

**Comment by xuchunyang** [comment]
That's not a problem for me since I am not a FireFox user and don't have many history records. I'm interested in the memory usage, just for curiosity. I made helm-chrome-history yesterday, with 41745 history items, it takes about 7 MiB.

```elisp
(length helm-chrome-history-candidates)
;; => 41745

(with-temp-buffer
  (prin1 helm-chrome-history-candidates (current-buffer))
  (file-size-human-readable (position-bytes (point-max))))
;; => "7.7M"
```

If users have too many history, they maybe worry about memory usage.

**Comment by cireu** [comment]
```
ELISP> (with-temp-buffer
         (prin1 counsel-ffdata--cache (current-buffer))
         (file-size-human-readable (position-bytes (point-max))))
"66.9M"
```

It may really cause memory crisis for somebody(small mem & using Firefox heavily)

**Comment by xuchunyang** [comment]
On my computer, each tab of Chrome takes about 60M memory, that's a lot, but I don't worry about it, since there is no difference for me between 20% and 60% memory usage rate, both are OK.
