### ISSUE TITLE
Cyrillic encoding issue

### ISSUE THREAD

**Issue by Pfedj** [cireu/counsel-ffdata#8]
Hello! Thank you for your work.

I have a problem with cyrillic encoding:
![Untitled](https://user-images.githubusercontent.com/11408619/66671013-cd317a00-ec63-11e9-98b8-cf04c63fc25d.png)

**Comment by cireu** [comment]
Hi! Sorry for my late reply. Are you using Windows system?

**Comment by Pfedj** [comment]
Hi again!
I use windows 10 but I have no such problem with [counsel-firefox-bookmark](https://github.com/tangxinfa/counsel-firefox-bookmarks)

**Comment by cireu** [comment]
I guess it's Windows' encoding issue, you know windows don't use utf-8 by default.

> I use windows 10 but I have no such problem with counsel-firefox-bookmark

It ask FF extracts bookmarks and history into XML with UTF-8 coding while we just read these data directly from FF's database.

**Comment by cireu** [comment]
Emm, I can't reproduce your issue under Windows 10 and Firefox 69 with this URL https://yandex.ru

![图片](https://user-images.githubusercontent.com/18224684/66995085-fdb06280-f100-11e9-92f1-5c52117def0c.png)

Can you give me more information about it? Like

- Firefox version
- sqlite3 version
- `M-x describe-variables RET w32-ansi-code-page RET`
- Run `sqlite3 <your ffdatabase> "SELECT bm.title, p.url FROM moz_bookmarks AS bm INNER JOIN moz_places AS p WHERE bm.fk = p.id;"` directly in CMD, will it output some regular data?

**Comment by Pfedj** [comment]
firefox 69.0.3
```
sqlite3 --version 
3.29.0 2019-07-10 17:32:03 fc82b73eaac8b36950e527f12c4b5dc1e147e6f4ad2217ae43ad82882a88alt2
```
``` 
M-x describe-variables RET w32-ansi-code-page RET 
Its value is 1251
```
with ```sqlite3 <your ffdatabase> "SELECT bm.title, p.url FROM moz_bookmarks AS bm INNER JOIN moz_places AS p WHERE bm.fk = p.id;"```  it works with cyrillic encoding in CMD.

**Comment by cireu** [comment]
```elisp
(defun gen-emacs-Q-command ()
  (interactive)
  (let ((cmd (mapconcat
              #'shell-quote-argument
              `(,(concat invocation-directory invocation-name)
                 "-Q" "--eval" "(setq debug-on-error t)"
                 ,@(cl-mapcan
                    (lambda (dir) (list "-L" dir))
                    (delete-dups
                     (cl-mapcan
                      (lambda (lib)
                        (let ((path (locate-library lib)))
                          (cond
                            (path
                             (list (file-name-directory path)))
                            ((not (equal lib "libgit"))
                             (error "Cannot find mandatory dependency %s" lib)))))
                      '(
                        "counsel"
                        "swiper"
                        "ivy"
                        "emacsql"
                        "counsel-ffdata"))))
                 ;; Avoid Emacs bug#16406 by using full path.
                 "-l" ,(file-name-sans-extension (locate-library "counsel-ffdata")))
              " ")))
    (kill-new cmd)))
```

Run this and it will generate a command(saved in your kill-ring) make you run Emacs with only `counsel-ffdata` and its dependencies loaded, can you reproduce issue in that environment?

**Comment by Pfedj** [comment]
It seems your function does not work on Windows cmd on the my machine. Perhaps there need to replace / with // and something else. 
Anyway I do it with 
```
(require 'counsel)
(require 'swiper)
(require 'ivy)
(require 'emacsql)
(require 'counsel-ffdata)
```
And with ```counsel-ffdata-firefox-bookmark``` there isn't problem with Cyrillic encoding. 
I have found ```(set-default-coding-systems 'windows-1251)``` 
which I changed to ```(set-default-coding-systems 'utf-8)```. And it solved the issue with encoding howewer now I have problems with encoding with opening files on my OS.

**Comment by cireu** [comment]
I guess #9 can solve your problem, please test if you can.

**Comment by Pfedj** [comment]
It works. Thank you!

**Comment by cireu** [comment]
I'll merge it into master :)
